### ISSUE TITLE
Add flag for http method

### ISSUE THREAD

**Issue by mattjegan** [mattjegan/wtfuzz#3]
Feature: `-m http_method` where http_method=GET|POST|PUT|PATCH
Relates to #4 

A user would use this flag to force the requests to be a different http method other than GET

**Comment by dbradf** [comment]
I put up a PR for to implement this flag, here: https://github.com/mattjegan/wtfuzz/pull/8

**Comment by mattjegan** [comment]
Thanks @dbradf , merged that PR in.
