### ISSUE TITLE
Flag for mapping codes to colours

### ISSUE THREAD

**Issue by mattjegan** [mattjegan/wtfuzz#5]
Feature: `-c pairs` where pairs is zero or more of the following `[http_statuscode, color]` and colour is  one of `red|green|yellow|blue|black|magenta|cyan|white` as used by [crayons](https://github.com/kennethreitz/crayons)

A user might want to customize the status codes they see most often.

**Comment by dbradf** [comment]
I opened a PR to implement this: https://github.com/mattjegan/wtfuzz/pull/11
