### ISSUE TITLE
Query parameter fuzzing

### ISSUE THREAD

**Issue by mattjegan** [mattjegan/wtfuzz#6]
At the moment, we only fuzz immediately after the url, we need some way to fuzz other things. Something like `wtfuzz http://my-url-here.com/somedata?i=$1&q=$2` where `$1` and `$2` indicates we should fuzz those locations in the url.

**Comment by prabodh1194** [comment]
These parameters will be made available from list_file. Like, for your e.g., above, list file can be a csv with

param1,param2
qwe,wer
asd,fwqw
azx,1a2

Appropriate checks and all can be made.
Does this sound (read?) fine?

**Comment by mattjegan** [comment]
@prabodh1194 That sounds fine to me, perhaps we could have a separate file for query param fuzzing? Or the option to brute force them

**Comment by prabodh1194** [comment]
> separate file for query param fuzzing

This is good, and then a cross product of entries in list_file and query param file
> brute force

Not sure of this part, query parameters can come in all formats. We'll need to auto generate these and that might be too complicated

**Comment by mattjegan** [comment]
That's a fair enough point, I'm happy with just the addition of the extra file.

**Comment by prabodh1194** [comment]
great.
