### ISSUE TITLE
Auto-detect whether we need to prepend protocol

### ISSUE THREAD

**Issue by mattjegan** [mattjegan/wtfuzz#7]
At the moment, wtfuzz requires the inclusion of `http://` or `https://` before a url so that `requests` doesn't error. This should be detected and added/prompted so that we don't crash.

Either:
```
wtfuzz myurlhere.com words.txt
Did you mean [1] http or [2] https? 
>> 1
```

or 

```
wtfuzz myurlhere.com words.txt
Prepending protocol: http://myurlhere.com
```

**Comment by dbradf** [comment]
I added a PR to implement this: https://github.com/mattjegan/wtfuzz/pull/10
